### ISSUE TITLE
Can I use it in plugins via Context params

### ISSUE THREAD

**Issue by Lahori-Jawan** [samtgarson/nuxt-env#12]
@samtgarson I am building docker image where I inject environment variables on runtime i.e. when creating container to specify production credentials. I am using nuxt apollo which requires to use plugin for dynamic `httpEndpoint` which of course is different than `localhost`. That's why I need to use this module inside plugins. is it possible? I thought it would be available via `ctx` param but found undefined.

**Comment by aalenliang** [comment]
i can get the variables from `ctx.app.$env`.
```
export default (ctx, inject) => {
  const { NODE_ENV, SITE_BASE_URL } = ctx.app.$env
  ...
}
```

**Comment by samtgarson** [comment]
As mentioned above the environment is available on `ctx.app.$env`, as long as you're running in universal mode. That use case is exactly what this module was designed for. 

Support for SPA mode will be added shortly.

**Comment by samtgarson** [comment]
Hi @albttx, for an OSS maintainer, that’s not a very useful comment. Please provide some details of what you’re doing and what’s not working, otherwise it’s very difficult to help you.

**Comment by albttx** [comment]
Hello @samtgarson,
Sorry you're absolutely right.

I'm in universal mode.
i need to get some environment variables at runtime.

in my plugins, i have 

```js
export default (ctx, inject) => {
  const FACEBOOK_APP_ID = ctx.app.$env.FACEBOOK_APP_ID
  console.log(ctx.app.$env) // empty
  ...
}
```

in my `nuxt.config.js`
```js
[
  'nuxt-env', {
      keys: [ { key: 'FACEBOOK_APP_ID' } ]
  }
]
```

then,

```sh
# generate .nuxt and dist
$ /node_modules/nuxt/bin/nuxt.js generate

$ FACEBOOK_APP_ID=foo ./node_modules/nuxt/bin/nuxt.js start
```
(this is to make a simpler example, my environment is injected inside a docker container)
