### ISSUE TITLE
VUEX env vars

### ISSUE THREAD

**Issue by robsontenorio** [samtgarson/nuxt-env#15]
I am trying to use an env var as initial state on VUEX. Both does not work, because `this` does not exists. Any tips?

```js
export const state = () => ({
  tv_mode: this.$env.TV_MODE
}
```

```js
const initialMode = this.$env.TV_MODE

export const state = () => ({
  tv_mode: initialMode
}
```

ERROR
```js
 ERROR  Cannot read property '$env' of undefined                                                                                                               22:48:42

  at o (webpack/bootstrap:2:0)
  at new Module (node_modules/vuex/dist/vuex.common.js:102:50)
  at ModuleCollection.register (node_modules/vuex/dist/vuex.common.js:191:19)
  at new ModuleCollection (node_modules/vuex/dist/vuex.common.js:162:8)
  at new Store (node_modules/vuex/dist/vuex.common.js:313:19)
  at Function (webpack/bootstrap:2:0)
  at Se (webpack/bootstrap:2:0)
```

**Comment by samtgarson** [comment]
`this` inside the store is the store instance itself, which has not been created at the time of that function being run.

You have two options:
- you could create a nuxt plugin which instantiates the store and will receive access to `app.$env`
- or more sensible would probably just to create a `bootstrap` mutation which you run when the app boots which loads the env vars in

**Comment by robsontenorio** [comment]
Just used nuxtInitServer() and called mutation for set initial state.
