### ISSUE TITLE
nuxt-community/dotenv-module 

### ISSUE THREAD

**Issue by robsontenorio** [samtgarson/nuxt-env#18]
Hi,

Have you considered submitting a PR for https://github.com/nuxt-community/dotenv-module ?

It would be nice to have both working in one place. Is it possible?

**Comment by samtgarson** [comment]
Right now I'm not sure where the value would lie in that. 

If you want to load in from `.env` you can install `dotenv` and run `const { parsed } =  require('dotenv').config()`

Then pass that to this module.

**Comment by nachogarcia** [comment]
Right now I'm connecting with dotenv with something like this
```
const { parsed: parsedEnv } = require('dotenv').config()

export default {
  mode: 'universal',
  modules: [
    '@nuxtjs/dotenv',
    ['nuxt-env', {
      keys: Object.entries(parsedEnv).map(([ key, value ]) => ({ key, default: value }))
    }],
 ...
```
While it takes the default value OK, I'm failing to change the values after the build (runtime).
Any suggestions @samtgarson ?
