### ISSUE TITLE
How to separate Development and Production Env?

### ISSUE THREAD

**Issue by PhouvanhKCSV** [samtgarson/nuxt-env#2]
As the documentation
```
// nuxt.config.js

// Tell nuxt-env which env vars you want to inject
modules: ['nuxt-env', {
  keys: ['TEST_VALUE']
}]
```

How can i separate Development and Production Env?

Example: i want TEST_VALUE = http://api.com (Production), TEST_VALUE = http://api.dev (Development)

**Comment by samtgarson** [comment]
`nuxt-env` takes environment variables from your environment—so however you normally set your env, you can continue to do so.

In development I'd recommend using something like [dotenv](https://www.npmjs.com/package/dotenv) for this, and include it as the first line in your `nuxt.config.js` (remember not to require it in production)
