### ISSUE TITLE
Passing vars at startup

### ISSUE THREAD

**Issue by ITElves** [samtgarson/nuxt-env#22]
I'm probably just too tired to see it, but I don't see any information about passing the variables into the npm start command line call. Is it just a matter of setting them to the same value in the nuxt config file?  

ENV_VAR=value npm start

**Comment by samtgarson** [comment]
That is out of the scope of this module—there are many ways of setting environment variables, depending on your local and production setups. 

Locally, I would suggest using [dotenv](https://www.npmjs.com/package/dotenv) to load environment variables, or the way you have specified will also work.

In production, it obviously depends on your setup but environment variables are usually an essential part of any production configuration. 

I would not recommend committing your env vars to your repo, as in that case you might as well use the native `env` option Nuxt already provides.

**Comment by samtgarson** [comment]
If you think this could be made clearer in the Readme, I'd accept a PR to fix that.
