### ISSUE TITLE
Use nuxt-env enviroment variables inside nuxt.config.js using

### ISSUE THREAD

**Issue by hussein661** [samtgarson/nuxt-env#28]
**nuxt.config.js**
```
module.exports = {
    ...
    gtm: {
      id: // how to access the variable NUXT_APP_GTM here
    },
    modules: [
      [
        'nuxt-env',
        {
          keys: [
            {
              key: 'NUXT_APP_GTM',
              default: 'GTM-XXXXXXX'
            },
          ]
        }
      ]
    ]
    ...
  }
  ```

is there a way to access the nuxt-env env variables for example something like :
```
    gtm: {
      id: NUXT_APP_GTM 
    }
```
or 
```
    gtm: {
      id: this.$env.NUXT_APP_GTM 
    }
```
NOT `process.env.NUXT_APP_GTM`

**Comment by PavelSavushkinMix** [comment]
https://github.com/samtgarson/nuxt-env/issues/20

**Comment by darkbluetech** [comment]
I ran into a similar issue trying to set the axios baseUrl within `nuxt.config.js` and solved it using a plugin, where the `$env` object is populated as expected. You might be able to do use a plugin too.

#30

**Comment by telliott22** [comment]
I ran into a similar issue trying to set the axios baseUrl within `nuxt.config.js` and solved it using a plugin, where the `$env` object is populated as expected. You might be able to do use a plugin too.

#30

**Comment by bagaskarala** [comment]
i'm try this plugin, but when i change variable in `.env` file, the value in app doesnt change. how to use this properly?

**Comment by samtgarson** [comment]
This plugin cannot control how other plugins use your values. 

I'd suggest you stop using this and start using the new official runtime config option that nuxt now has. 

I'd also suggest you open issues (or support existing ones) on the plugins that aren't working (e.g. nuxt axios, gtm, etc) as they need to switch to support runtime configuration they don't already.
