### ISSUE TITLE
How to inject env variable into axios?

### ISSUE THREAD

**Issue by asolopovas** [samtgarson/nuxt-env#30]
Hi, 

Is there a way to inject env variable directly into axios plugin? The problem is that all the ways it can be injected as shown in docs env variables are either injected via store method or component. How can access runtime env variables in global scope?
If I am doing the following it does work in server-side but on the front end, it says it is undefined.

```js
import https from 'https'
import axios from 'axios'

const baseURL = process.env.APP_URL

export default axios.create({
  baseURL: `https://${baseURL}/api/`,
  httpsAgent: new https.Agent({
    rejectUnauthorized: false
  })
})
```

Thanks.

**Comment by darkbluetech** [comment]
I had the same issue and managed to work around using an [axios interceptor](https://github.com/axios/axios#interceptors) inside a  plugin. 

`axios.js`

```
export default (context, inject) => {

// Before each request is made, update the axios baseUrl with the env variable
    context.app.$axios.interceptors.request.use(function (config) {
        
        const apiUrl = context.app.$env.API_URL;
  
        config.baseURL = apiUrl;

        return config;
      });
    
  }

```

`nuxt.config.js`

```
plugins: [
    ...
    '~/plugins/axios.js',
    ...
  ],
```

**Comment by percenuage** [comment]
@telliott22 Thank you it works!!! I think it should be better not to use interceptor but to directly include the fonctionality in `nuxt-env` module.

**Comment by samtgarson** [comment]
It's nothing to do with `nuxt-env`, what you're asking isn't possible as you've written it. 

You can use a Nuxt plugin and export a function, which will be given the context as a first argument and an injection function as a second:

```js
// plugins/axios.js

export default (ctx, inject) => {
  const baseUrl = ctx.app.$env.BASE_URL
  const client = axios.create(...)

  inject('axios', client)
}
```

`$axios` will then be available in your components, store, etc. If you need access to it otherwise, you can do something like this:

```js
// plugins/axios.js

let client
export default (ctx, inject) => {
  const baseUrl = ctx.app.$env.BASE_URL
  client = axios.create(...)
}

export const axios = client
```
