### ISSUE TITLE
Error: inject('env', value) has no value provided

### ISSUE THREAD

**Issue by iandevlin** [samtgarson/nuxt-env#35]
Hi,
I am fairly new to Nuxt and what comes with it in general, so please forgive me if this is a dumb question.

I currently have `ssr: false;` set in my `nuxt.config.js` file and keep getting the above error.

I took a look into `client.js` and notice that it says:
```
const env = ctx.nuxtState !== undefined ? ctx.nuxtState.env : ctx.env
```
in the `client()` function.

I took a look at `ctx` and found that `nuxtState` does indeed exist, but it only contains `config: {}` and nothing more, hence of course this check is failing.

If I set it to:
```
const env = ctx.nuxtState !== undefined && ctx.nuxtState.env !== undefined ? ctx.nuxtState.env : ctx.env
```
it works fine, because of course now it uses `ctx.env`.

So I am wondering, is this a bug in the code, or is there something weirder going on in my setup that is causing `nuxtState` to be defined, but empty?

Any help would be appreciated!

**Comment by samtgarson** [comment]
Hey @iandevlin, at the moment this library only works with SSR switched on at the moment, as it needs to take the environment variables from the server environment.

There is a thread [here](https://github.com/samtgarson/nuxt-env/issues/7) with some discussion around making this work without SSR but I would advise switching to Runtime Config which has been released in Nuxt.js and can replace this package.
